-- DDL esperado das entidades JPA do HemoLife, gerado pelo Hibernate nos testes.
-- Referencia para um schema novo. Nao e uma migracao de tabelas com dados existentes.
-- Este arquivo nao e executado automaticamente pela aplicacao.
-- Consulte docs/migracao-dominio.md para tipos adotados e decisoes de compatibilidade.
create table exames (data_exame date not null, horario time(6) not null, criado_em timestamp(6) not null, id bigint generated by default as identity, ong_id bigint not null, unidade_id bigint not null, usuario_id bigint not null, status varchar(20) not null check (status in ('AGENDADO','CANCELADO')), arquivo_id varchar(24), primary key (id), constraint uk_exames_usuario_data_horario unique (usuario_id, data_exame, horario), constraint ck_exames_horario_minuto check (extract(second from horario) = 0));
create table inscricao (id bigint generated by default as identity, ong_id bigint not null, usuario_id bigint not null, primary key (id), constraint uk_inscricao_usuario_ong unique (usuario_id, ong_id));
create table ong (id bigint generated by default as identity, cnpj varchar(18) not null, email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id), constraint uk_ong_email unique (email), constraint uk_ong_cnpj unique (cnpj));
create table unidades (id bigint generated by default as identity, telefone varchar(30) not null, endereco varchar(500) not null, nome varchar(255) not null, primary key (id));
create table usuarios (id bigint generated by default as identity, perfil varchar(10) not null, tipo_sanguineo varchar(10), email varchar(255) not null, nome varchar(255) not null, senha varchar(255) not null, primary key (id), constraint uk_usuarios_email unique (email), constraint ck_usuarios_perfil check (perfil in ('admin', 'doador')), constraint ck_usuarios_doador_tipo check (perfil <> 'doador' or (tipo_sanguineo is not null and length(trim(tipo_sanguineo)) > 0)));
alter table if exists exames add constraint fk_exames_ong foreign key (ong_id) references ong;
alter table if exists exames add constraint fk_exames_unidade foreign key (unidade_id) references unidades;
alter table if exists exames add constraint fk_exames_usuario foreign key (usuario_id) references usuarios;
alter table if exists inscricao add constraint fk_inscricao_ong foreign key (ong_id) references ong;
alter table if exists inscricao add constraint fk_inscricao_usuario foreign key (usuario_id) references usuarios;
